from datetime import datetime, timezone
from sqlalchemy import JSON, DateTime, ForeignKey, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from core.persistence.database import Base
def now(): return datetime.now(timezone.utc)
class DatasetEntity(Base):
 __tablename__="datasets"; id:Mapped[str]=mapped_column(String,primary_key=True); external_id:Mapped[str|None]=mapped_column(String,nullable=True); name:Mapped[str|None]=mapped_column(String,nullable=True); description:Mapped[str|None]=mapped_column(Text,nullable=True); provenance:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class DatasetVersionEntity(Base):
 __tablename__="dataset_versions"; __table_args__=(UniqueConstraint("dataset_id","version"),); id:Mapped[str]=mapped_column(String,primary_key=True); dataset_id:Mapped[str]=mapped_column(ForeignKey("datasets.id",ondelete="RESTRICT")); version:Mapped[str|None]=mapped_column(String,nullable=True); content_hash:Mapped[str|None]=mapped_column(String,nullable=True); payload:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ModelConfigEntity(Base):
 __tablename__="model_configs"; id:Mapped[str]=mapped_column(String,primary_key=True); model_name:Mapped[str]=mapped_column(String); payload:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class BenchmarkRunEntity(Base):
 __tablename__="benchmark_runs"; id:Mapped[str]=mapped_column(String,primary_key=True); model_config_id:Mapped[str]=mapped_column(ForeignKey("model_configs.id",ondelete="RESTRICT")); dataset_version_id:Mapped[str|None]=mapped_column(ForeignKey("dataset_versions.id",ondelete="RESTRICT"),nullable=True); status:Mapped[str]=mapped_column(String); payload:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class EvaluationResultEntity(Base):
 __tablename__="evaluation_results"; id:Mapped[str]=mapped_column(String,primary_key=True); benchmark_run_id:Mapped[str]=mapped_column(ForeignKey("benchmark_runs.id",ondelete="RESTRICT")); case_id:Mapped[str|None]=mapped_column(String,nullable=True); execution_status:Mapped[str]=mapped_column(String); prompt:Mapped[str|None]=mapped_column(Text,nullable=True); response:Mapped[str|None]=mapped_column(Text,nullable=True); latency_ms:Mapped[float|None]=mapped_column(nullable=True); hierarchy:Mapped[dict]=mapped_column(JSON,default=dict); provider_metadata:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class LayerOneResultEntity(Base):
 __tablename__="layer1_results"; id:Mapped[str]=mapped_column(String,primary_key=True); evaluation_result_id:Mapped[str]=mapped_column(ForeignKey("evaluation_results.id",ondelete="RESTRICT")); detector_name:Mapped[str]=mapped_column(String); score:Mapped[float]=mapped_column(); confidence:Mapped[float|None]=mapped_column(nullable=True); payload:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class LayerTwoResultEntity(Base):
 __tablename__="layer2_results"; id:Mapped[str]=mapped_column(String,primary_key=True); evaluation_result_id:Mapped[str]=mapped_column(ForeignKey("evaluation_results.id",ondelete="RESTRICT")); dimension:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String); score:Mapped[float|None]=mapped_column(nullable=True); confidence:Mapped[float|None]=mapped_column(nullable=True); payload:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ScientificRecordEntity(Base):
 __tablename__="scientific_records"; id:Mapped[str]=mapped_column(String,primary_key=True); family:Mapped[str]=mapped_column(String); schema_version:Mapped[str]=mapped_column(String); scope:Mapped[str]=mapped_column(String); owner_id:Mapped[str|None]=mapped_column(String,nullable=True); status:Mapped[str|None]=mapped_column(String,nullable=True); payload:Mapped[dict]=mapped_column(JSON); provenance:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ScientificReviewEntity(Base):
 __tablename__="scientific_reviews"; id:Mapped[str]=mapped_column(String,primary_key=True); claim_id:Mapped[str]=mapped_column(String); evidence_bundle_id:Mapped[str]=mapped_column(String); reviewer_protocol:Mapped[str]=mapped_column(String); decision:Mapped[str]=mapped_column(String); rationale:Mapped[str]=mapped_column(Text); provenance:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
