import { MetricReadiness } from "../components/common/MetricReadiness";
import { ScientificRecordsPage } from "./ScientificRecordsPage";

export function BSDAPage() { return <ScientificRecordsPage title="Behavior Stability Detection Algorithm" family="bsda" intro="BSDA computes and preserves a component vector. No composite BSDA score is calculated or rendered."><MetricReadiness implementation="Implemented" calibration="Not established" detail="Semantic, safety, instruction, and structural distances remain separately inspectable; calibration cannot be inferred from a component value." /><h2>Independent component evidence</h2><ul><li>Semantic distance</li><li>Safety distance</li><li>Instruction distance</li><li>Structural distance</li></ul><p>Uncertainty is displayed only if an upstream payload contains an uncertainty artifact; no ± values are inferred.</p></ScientificRecordsPage>; }
export function RecoveryPage() { return <ScientificRecordsPage title="Recovery Capability" family="rc" intro="RC payloads are lossless Phase 11 records. Typed RC fields, trajectories, and recovery-latency diagnostics are not inferred by the frontend."><MetricReadiness implementation="Implemented" calibration="Not established" detail="Raw recovery trajectories are preserved as source data; a calibration study is required before using them as risk or selection scores." /></ScientificRecordsPage>; }
export function SAEAPage() { return <ScientificRecordsPage title="Sequential Attack Evaluation Algorithm" family="saea" intro="Sequence-level records retain their upstream applicability and status contract. CV_obs means observed cumulative vulnerability; it is not an attack-success statistic."><MetricReadiness implementation="Implemented" calibration="Experimental" detail="The sequence computations run when a qualified sequence artifact exists. Candidate Bliss analysis remains experimental." /><p>No sequence-length rule or recovery-failure percentage is invented by this interface.</p></ScientificRecordsPage>; }
export function DRAAPage() { return <ScientificRecordsPage title="Dynamic Risk Assessment Algorithm" family="draa" intro="Mode A/B evidence extraction is available. DRAA does not expose a scalar risk score in this dashboard."><MetricReadiness implementation="Implemented (Modes A/B)" calibration="Not established" detail="The system extracts structured evidence features. A scalar risk score needs a separately validated calibration and is therefore intentionally absent." /><p>Mode C is not available.</p></ScientificRecordsPage>; }
export function PRIPage() { return <ScientificRecordsPage title="Prompt Robustness Index" family="pri" intro="PRI is an implemented descriptive, profile-based record. It is not converted to a scalar, grade, ranking, or robustness conclusion."><MetricReadiness implementation="Implemented profile" calibration="Not established" detail="Profile cells and coverage are computed from persisted evidence. There is no validated scalar PRI decision rule." /></ScientificRecordsPage>; }
export function DQIPage() { return <ScientificRecordsPage title="Dataset Quality Index" family="dqi" intro="DQI computes the source-native diagnostic components and preserves their provenance."><MetricReadiness implementation="Implemented diagnostic" calibration="Exploratory" detail="The existing DQI formula runs, but its diagnostic value has not been validated as a universal dataset-quality conclusion." /></ScientificRecordsPage>; }
export function MLPredictionPage() { return <ScientificRecordsPage title="ML Prediction" family="ml" intro="The supervised ML pipeline is implemented with prevalence and L2 logistic-regression contracts. It activates only when independent labels, an admissible feature schema, and a split manifest exist."><MetricReadiness implementation="Implemented pipeline" calibration="Blocked pending labels" detail="No production outcome labels are currently persisted, so predictive quality cannot be computed honestly." /></ScientificRecordsPage>; }
export function StatisticalPage() { return <ScientificRecordsPage title="Statistical Analysis" family="statistics" intro="Computed Phase 10 artifacts are displayed from persisted upstream records. The frontend does not manufacture p-values, effect sizes, intervals, or validation conclusions."><MetricReadiness implementation="Implemented descriptive statistics" calibration="Not applicable" detail="Latency and other descriptive calculations can be computed from recorded runs; inferential claims require an appropriate experimental design." /></ScientificRecordsPage>; }
