import { ScientificStatusBadge } from "../components/common/ScientificStatusBadge";
import { ScientificRecordsPage } from "./ScientificRecordsPage";

export function BSDAPage() { return <ScientificRecordsPage title="Behavior Stability Detection Algorithm" family="bsda" intro="BSDA is displayed as an exploratory component vector. No composite BSDA score is calculated or rendered."><ScientificStatusBadge /><h2>Independent component evidence</h2><ul><li>Semantic distance</li><li>Safety distance</li><li>Instruction distance</li><li>Structural distance</li></ul><p>Uncertainty is displayed only if an upstream payload contains an uncertainty artifact; no ± values are inferred.</p></ScientificRecordsPage>; }
export function RecoveryPage() { return <ScientificRecordsPage title="Recovery Capability" family="rc" intro="RC payloads are lossless Phase 11 records. Typed RC fields, trajectories, and recovery-latency diagnostics are not inferred by the frontend."><ScientificStatusBadge /></ScientificRecordsPage>; }
export function SAEAPage() { return <ScientificRecordsPage title="Sequential Attack Evaluation Algorithm" family="saea" intro="Sequence-level records retain their upstream applicability and status contract. CV_obs means observed cumulative vulnerability; it is not an attack-success statistic."><ScientificStatusBadge /><p>No sequence-length rule or recovery-failure percentage is invented by this interface.</p></ScientificRecordsPage>; }
export function DRAAPage() { return <ScientificRecordsPage title="Dynamic Risk Assessment Algorithm" family="draa" intro="Only Mode A/B evidence and uncalibrated diagnostics are represented. DRAA does not expose a scalar risk score in this dashboard."><ScientificStatusBadge status="UNCALIBRATED" /><p>Mode C is not available.</p></ScientificRecordsPage>; }
export function PRIPage() { return <ScientificRecordsPage title="Prompt Robustness Index" family="pri" intro="PRI remains a descriptive, profile-based record. It is not converted to a scalar, grade, ranking, or robustness conclusion."><ScientificStatusBadge status="UNCALIBRATED" /></ScientificRecordsPage>; }
export function DQIPage() { return <ScientificRecordsPage title="Dataset Quality Index" family="dqi" intro="DQI is EXPLORATORY and NOT SCIENTIFICALLY VALIDATED. Source-native components are preserved without a new formula."><ScientificStatusBadge /></ScientificRecordsPage>; }
export function MLPredictionPage() { return <ScientificRecordsPage title="ML Prediction" family="ml" intro="Only persisted engineering artifacts and their explicit validation/calibration status are displayed. No performance statistic is fabricated."><ScientificStatusBadge /></ScientificRecordsPage>; }
export function StatisticalPage() { return <ScientificRecordsPage title="Statistical Analysis" family="statistics" intro="Only computed Phase 10 artifacts persisted upstream are displayed. The frontend does not manufacture p-values, effect sizes, intervals, or validation conclusions."><ScientificStatusBadge /></ScientificRecordsPage>; }
